/**
 * Agent Trace Store
 *
 * Agent Trace specification (v0.1.0) compliant trace storage library
 * https://agent-trace.dev/
 *
 * Tracks AI-generated code provenance: who wrote what, which model,
 * which commit, which agent/skill/workflow was involved.
 *
 * @version 1.0.0
 * @license MIT
 */

import * as fs from 'fs';
import * as path from 'path';
import * as crypto from 'crypto';

// ============================================
// Type Definitions (Agent Trace Spec v0.1.0)
// ============================================

/**
 * Contributor type
 * - human: directly written by a human
 * - ai: generated by AI
 * - mixed: human-edited AI code, or AI-edited human code
 * - unknown: origin unknown
 */
export type ContributorType = 'human' | 'ai' | 'mixed' | 'unknown';

/**
 * Line range
 */
export interface TraceRange {
  start_line: number;
  end_line: number;  // -1 = to end of file
}

/**
 * Conversation/edit session info
 */
export interface Conversation {
  contributor_type: ContributorType;
  model?: string;
  ranges: TraceRange[];
  context_url?: string;
  description?: string;
}

/**
 * Per-file trace info
 */
export interface FileTrace {
  path: string;
  conversations: Conversation[];
}

/**
 * VCS (Version Control System) info
 */
export interface VcsInfo {
  type: 'git' | 'jj' | 'hg' | 'svn';
  commit?: string;
  branch?: string;
}

/**
 * Tool info
 */
export interface ToolInfo {
  name: string;
  version: string;
}

/**
 * EM-Team specific metadata
 */
export interface EmTeamMetadata {
  skill_used?: string;
  agent_id?: string;
  workflow_phase?: string;
  session_id?: string;
}

/**
 * Agent Trace Record (main data structure)
 */
export interface TraceRecord {
  version: string;
  id: string;
  timestamp: string;
  files: FileTrace[];
  vcs?: VcsInfo;
  tool?: ToolInfo;
  metadata?: {
    'dev.em-team'?: EmTeamMetadata;
    [key: string]: unknown;
  };
}

// ============================================
// TraceStore Class
// ============================================

export class TraceStore {
  private projectRoot: string;
  private traceDir: string;
  private readonly SPEC_VERSION = '0.1.0';
  private readonly TOOL_NAME = 'em-team';

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
    this.traceDir = path.join(projectRoot, '.agent-trace', 'traces');
    this.ensureDir();
  }

  private ensureDir(): void {
    if (!fs.existsSync(this.traceDir)) {
      fs.mkdirSync(this.traceDir, { recursive: true });
    }
  }

  private generateUUID(): string {
    return crypto.randomUUID();
  }

  private getGitCommit(): string | undefined {
    try {
      const gitDir = path.join(this.projectRoot, '.git');
      if (!fs.existsSync(gitDir)) return undefined;

      const headPath = path.join(gitDir, 'HEAD');
      const headContent = fs.readFileSync(headPath, 'utf-8').trim();

      if (headContent.startsWith('ref: ')) {
        const refPath = path.join(gitDir, headContent.slice(5));
        if (fs.existsSync(refPath)) {
          return fs.readFileSync(refPath, 'utf-8').trim().slice(0, 40);
        }
      }
      return headContent.slice(0, 40);
    } catch {
      return undefined;
    }
  }

  private getGitBranch(): string | undefined {
    try {
      const gitDir = path.join(this.projectRoot, '.git');
      const headPath = path.join(gitDir, 'HEAD');
      const headContent = fs.readFileSync(headPath, 'utf-8').trim();

      if (headContent.startsWith('ref: refs/heads/')) {
        return headContent.slice('ref: refs/heads/'.length);
      }
      return undefined;
    } catch {
      return undefined;
    }
  }

  private getEmTeamVersion(): string {
    try {
      const packagePath = path.join(this.projectRoot, 'package.json');
      if (fs.existsSync(packagePath)) {
        const pkg = JSON.parse(fs.readFileSync(packagePath, 'utf-8'));
        return pkg.version || '2.2.0';
      }
    } catch {
      // ignore
    }
    return process.env.EM_TEAM_VERSION || '2.2.0';
  }

  createTrace(files: FileTrace[], emTeamMeta?: EmTeamMetadata): TraceRecord {
    const trace: TraceRecord = {
      version: this.SPEC_VERSION,
      id: this.generateUUID(),
      timestamp: new Date().toISOString(),
      files,
      vcs: {
        type: 'git',
        commit: this.getGitCommit(),
        branch: this.getGitBranch()
      },
      tool: {
        name: this.TOOL_NAME,
        version: this.getEmTeamVersion()
      },
      metadata: {
        'dev.em-team': emTeamMeta || {}
      }
    };

    if (!trace.vcs?.commit) {
      delete trace.vcs;
    }

    return trace;
  }

  createFileEditTrace(
    filePath: string,
    contributorType: ContributorType = 'ai',
    model: string = 'anthropic/claude-opus-4-7',
    description?: string,
    emTeamMeta?: EmTeamMetadata
  ): TraceRecord {
    const relativePath = path.isAbsolute(filePath)
      ? path.relative(this.projectRoot, filePath)
      : filePath;

    const files: FileTrace[] = [{
      path: relativePath,
      conversations: [{
        contributor_type: contributorType,
        model,
        ranges: [{ start_line: 1, end_line: -1 }],
        description
      }]
    }];

    return this.createTrace(files, emTeamMeta);
  }

  save(trace: TraceRecord): string {
    const date = trace.timestamp.split('T')[0];
    const shortId = trace.id.slice(0, 8);
    const filename = `${date}_${shortId}.json`;
    const filepath = path.join(this.traceDir, filename);

    fs.writeFileSync(filepath, JSON.stringify(trace, null, 2), 'utf-8');
    return filepath;
  }

  saveFileEditTrace(
    filePath: string,
    contributorType: ContributorType = 'ai',
    model?: string,
    description?: string,
    emTeamMeta?: EmTeamMetadata
  ): string {
    const trace = this.createFileEditTrace(
      filePath,
      contributorType,
      model,
      description,
      emTeamMeta
    );
    return this.save(trace);
  }

  list(limit: number = 0): TraceRecord[] {
    if (!fs.existsSync(this.traceDir)) {
      return [];
    }

    const files = fs.readdirSync(this.traceDir)
      .filter(f => f.endsWith('.json'))
      .sort()
      .reverse();

    const targetFiles = limit > 0 ? files.slice(0, limit) : files;

    return targetFiles.map(f => {
      const content = fs.readFileSync(path.join(this.traceDir, f), 'utf-8');
      return JSON.parse(content) as TraceRecord;
    });
  }

  findByFile(filePath: string): TraceRecord[] {
    const relativePath = path.isAbsolute(filePath)
      ? path.relative(this.projectRoot, filePath)
      : filePath;

    return this.list().filter(trace =>
      trace.files.some(f => f.path === relativePath)
    );
  }

  findByDateRange(startDate: string, endDate: string): TraceRecord[] {
    return this.list().filter(trace => {
      const date = trace.timestamp.split('T')[0];
      return date >= startDate && date <= endDate;
    });
  }

  getStatistics(): {
    total: number;
    byContributorType: Record<ContributorType, number>;
    byModel: Record<string, number>;
    byDate: Record<string, number>;
  } {
    const traces = this.list();

    const stats = {
      total: traces.length,
      byContributorType: { human: 0, ai: 0, mixed: 0, unknown: 0 } as Record<ContributorType, number>,
      byModel: {} as Record<string, number>,
      byDate: {} as Record<string, number>
    };

    for (const trace of traces) {
      const date = trace.timestamp.split('T')[0];
      stats.byDate[date] = (stats.byDate[date] || 0) + 1;

      for (const file of trace.files) {
        for (const conv of file.conversations) {
          stats.byContributorType[conv.contributor_type]++;
          if (conv.model) {
            stats.byModel[conv.model] = (stats.byModel[conv.model] || 0) + 1;
          }
        }
      }
    }

    return stats;
  }

  archive(daysToKeep: number = 30): number {
    const archiveDir = path.join(this.projectRoot, '.agent-trace', 'archive');
    if (!fs.existsSync(archiveDir)) {
      fs.mkdirSync(archiveDir, { recursive: true });
    }

    const cutoffDate = new Date();
    cutoffDate.setDate(cutoffDate.getDate() - daysToKeep);
    const cutoffStr = cutoffDate.toISOString().split('T')[0];

    let archivedCount = 0;
    const files = fs.readdirSync(this.traceDir).filter(f => f.endsWith('.json'));

    for (const file of files) {
      const date = file.split('_')[0];
      if (date < cutoffStr) {
        const src = path.join(this.traceDir, file);
        const dest = path.join(archiveDir, file);
        fs.renameSync(src, dest);
        archivedCount++;
      }
    }

    return archivedCount;
  }

  getTraceDir(): string {
    return this.traceDir;
  }
}

// ============================================
// Utility Functions
// ============================================

export function getDefaultTraceStore(): TraceStore {
  const projectRoot = process.cwd();
  return new TraceStore(projectRoot);
}

export function quickTrace(
  filePath: string,
  description?: string
): string {
  const store = getDefaultTraceStore();
  return store.saveFileEditTrace(filePath, 'ai', undefined, description);
}

// CommonJS compatible export
module.exports = { TraceStore, getDefaultTraceStore, quickTrace };
