#!/bin/bash
#
# EM-Team Session Handoff Generator
# Inspired by: TAISUN session-handoff pattern
#
# Creates a SESSION_HANDOFF.md file preserving context between sessions
# Usage: Run manually or via Claude Code hook at session end
#

HANDOFF_FILE="SESSION_HANDOFF.md"
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
BRANCH=$(git branch --show-current 2>/dev/null || echo "unknown")
LATEST_COMMIT=$(git log -1 --pretty=format:"%h %s" 2>/dev/null || echo "none")
UNCOMMITTED=$(git status --short 2>/dev/null | head -20 || echo "none")

cat > "$HANDOFF_FILE" << EOF
# Session Handoff

**Generated:** $TIMESTAMP
**Branch:** $BRANCH
**Latest commit:** $LATEST_COMMIT

## Current State

### Uncommitted Changes
\`\`\`
$UNCOMMITTED
\`\`\`

### Modified Files (this session)
$(git diff --name-only HEAD~5 2>/dev/null | sed 's/^/- /' || echo "- none tracked")

## Active Work

<!-- Describe what was being worked on. AI: fill this section before ending session. -->

## Completed This Session

<!-- List completed tasks. AI: fill this section before ending session. -->

## Blocked / Needs Context

<!-- List items that need user input. AI: fill this section before ending session. -->

## Next Steps

<!-- Recommended actions for the next session. AI: fill this section before ending session. -->

## Key Decisions Made

<!-- Record any important decisions and why. AI: fill this section before ending session. -->

---

*This file is auto-generated by session-handoff.sh. Update the Active Work and Next Steps sections before ending your session.*
EOF

echo "Session handoff written to $HANDOFF_FILE"
